################################################################
#	Makefile
################################################################
all:
#	(cd benchmarks; $(MAKE) all)
	(cd java; $(MAKE) all)
	(cd plcafe; $(MAKE) all)
	(cd prolog; $(MAKE) all)

clean:
	-rm -f core *~
#	(cd benchmarks; $(MAKE) clean)
	(cd java; $(MAKE) clean)
	(cd plcafe; $(MAKE) clean)
	(cd prolog; $(MAKE) clean)

realclean:
	-rm -f core *~
#	(cd benchmarks; $(MAKE) realclean)
	(cd java; $(MAKE) realclean)
	(cd plcafe; $(MAKE) realclean)
	(cd prolog; $(MAKE) realclean)

